# Generated by Django 4.1.1 on 2022-10-07 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='completiondate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
